### ISSUE TITLE
路徑bug

### ISSUE THREAD

**Issue by spetacular** [appleboy/php-i18n#1]
我用了這個類，發現index.php與Language.php在同一路徑下時可用.如果index.php不與Language.php同一路徑，如Language.php和language目錄在根目錄下，index.php在test目錄下，則發生錯誤

**Comment by appleboy** [comment]
感謝回報，明天會進行測試 ~ 有任何進展會回覆到此處

**Comment by spetacular** [comment]
if (file_exists('language/'.$idiom.'/'.$langfile))
        {
            include('language/'.$idiom.'/'.$langfile);
}

是這裡，如果不在同一路徑下，language/'.$idiom.'/'.$langfile會找不到文件。可能原因是include包含相對路徑。

**Comment by spetacular** [comment]
$absolutelangfile=dirname(**FILE**).'/language/'.$idiom.'/'.$langfile;
 if (file_exists($absolutelangfile))
{
     include($absolutelangfile);
}
使用絕對路徑能消除此問題
